---
engines:
  eslint:
    enabled: true
  duplication:
    enabled: true
    channel: cronopio
    config:
      languages:
      - ruby
  complexity-ruby:
    enabled: true
    channel: beta
exclude_paths:
- spec/**/*
- "**/vendor/**/*"
- test/**
