JavaScript: true
engines:
  eslint:
    enabled: true
    checks:
      global-require:
        enabled: false
  duplication:
    enabled: false
    config:
      languages:
      - javascript
ratings:
  paths:
  - lib/**
exclude_paths:
- spec/**/*
- "**/vendor/**/*"
- test/**